package proyecto_2;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author forza
 */
public class Vista extends javax.swing.JFrame {

    private JLabel texto;
    private JTextField texto_velocidadMaxima;
    private JTextArea texto_vehiculos;
    private JButton boton, boton2, boton3;
    
    private GestorVehiculo gestor;
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
        gestor = new GestorVehiculo();
        
        texto = new JLabel("Velocidad máxima: ");
        texto.setSize(120, 40);
        texto.setPreferredSize(new Dimension(120, 40));
        texto.setLocation(10, 0);
        texto.setVisible(true);
        
        texto_velocidadMaxima = new JTextField("300");
        texto_velocidadMaxima.setSize(120, 20);
        texto.setPreferredSize(new Dimension(120, 40));
        texto_velocidadMaxima.setLocation(120, 10);
        texto_velocidadMaxima.setVisible(true);
        
        boton = new JButton("Crear coche");
        boton.setSize(120, 30);
        boton.setPreferredSize(new Dimension(120, 30));
        boton.setLocation(10, 40);
        boton.setVisible(true);
        
        boton2 = new JButton("Crear moto");
        boton2.setSize(120, 30);
        boton2.setPreferredSize(new Dimension(120, 30));
        boton2.setLocation(120, 40);
        boton2.setVisible(true);
        
        boton3 = new JButton("Incrementar velocidad");
        boton3.setSize(162, 30);
        boton3.setPreferredSize(new Dimension(162, 30));
        boton3.setLocation(230, 40);
        boton3.setVisible(true);
        
        texto_vehiculos = new JTextArea();
        texto_vehiculos.setLocation(10, 80);
        texto_vehiculos.setAutoscrolls(true);
        texto_vehiculos.setEditable(false);
        texto_vehiculos.setWrapStyleWord(true);
        texto_vehiculos.setLineWrap(true); // Ajusta el texto dentro del área automáticamente
        texto_vehiculos.setVisible(true);
        
        JScrollPane scroll = new JScrollPane(texto_vehiculos);
        scroll.setSize(380, 140);
        scroll.setLocation(0, 80);
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scroll.setVisible(true);

        
        boton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Coche c = new Coche(Integer.parseInt(texto_velocidadMaxima.getText()), 0, 50, 50, 4);
                gestor.addVehiculo(c);
                texto_vehiculos.setText(gestor.mostrarVehiculos());
                texto_vehiculos.setCaretPosition(texto_vehiculos.getDocument().getLength());
                
                texto_vehiculos.setCaretPosition(texto_vehiculos.getDocument().getLength());

                texto_vehiculos.revalidate();
                texto_vehiculos.repaint();

            }
        });
        
        boton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Moto m = new Moto(Integer.parseInt(texto_velocidadMaxima.getText()), 0, 30, 30, true);
                gestor.addVehiculo(m);
                texto_vehiculos.setText(gestor.mostrarVehiculos());
                texto_vehiculos.setCaretPosition(texto_vehiculos.getDocument().getLength());
                
                texto_vehiculos.setCaretPosition(texto_vehiculos.getDocument().getLength());

                texto_vehiculos.revalidate();
                texto_vehiculos.repaint();

            }
        });
        
        boton3.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Vehiculo v = gestor.gestor.getLast();
                v.aumentarMedia();
                
                texto_vehiculos.setText(gestor.mostrarVehiculos());
                texto_vehiculos.setCaretPosition(texto_vehiculos.getDocument().getLength());
                
                texto_vehiculos.setCaretPosition(texto_vehiculos.getDocument().getLength());

                texto_vehiculos.revalidate();
                texto_vehiculos.repaint();
            }
            
        });
        
        this.add(texto);
        this.add(texto_velocidadMaxima);
        this.add(boton);
        this.add(boton2);
        this.add(boton3);
        this.add(scroll);
        
        this.getGraphics();
        this.repaint();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
